// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWcoRfukr7m2oKQATRl6zwFpFgKiKaiU',
    appId: '1:373673004040:android:0b76fa86f22853c1d255bd',
    messagingSenderId: '373673004040',
    projectId: 'gestao-imobiliaria-app',
    storageBucket: 'gestao-imobiliaria-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFwf0QlOF9AHfWWbuOUX2lK7ElV2s8kxA',
    appId: '1:373673004040:ios:b996a264af49868dd255bd',
    messagingSenderId: '373673004040',
    projectId: 'gestao-imobiliaria-app',
    storageBucket: 'gestao-imobiliaria-app.appspot.com',
    iosBundleId: 'com.example.gestaoDeImobiliariaMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH2O8GDWGuUGNNquS4UHNH5HYbjARDbqw',
    appId: '1:373673004040:web:7cf6ea1f087fdcaed255bd',
    messagingSenderId: '373673004040',
    projectId: 'gestao-imobiliaria-app',
    authDomain: 'gestao-imobiliaria-app.firebaseapp.com',
    storageBucket: 'gestao-imobiliaria-app.appspot.com',
  );
}
